python main.py \
    --sh_file_name                          main_T2I_StableDiffusion_null_space_projection.sh           \
    --device                                cuda:0                                      \
    --model_name                            stabilityai/stable-diffusion-2-1-base                      \
    --mask_model_name                       facebook/sam-vit-large                      \
    --dataset_name                          Random                                      \
    --edit_prompt                           "a photo of a man wearing glasses"                  \
    --for_prompt                            "a photo of a man"                          \
    --neg_prompt                            ""                                          \
    --x_space_guidance_scale                8.0                                         \
    --x_space_guidance_num_step             1                                          \
    --edit_t                                0.7                                         \
    --run_edit_null_space_projection_zt_semantic     True                                        \
    --note                                  "with_prompt"                               \
    --guidance_scale                        7.5                                         \
    --guidance_scale_edit                   4.0                                         \
    --seed                                  305186554                                  \
    --null_space_projection                 True                                        \
    --pca_rank_null                         5                                           \
    --pca_rank                              1                                           \
    --sampling_mode                         False                                       \
    --mask_index                            1                                           \
    --tilda_v_score_type                    "null+(for-null)+(edit-null)"                          \
    --cache_folder                          <TODO>        \
    --dtype                                 fp32                                        \
    --vis_num                               1                                           \
    --use_sega                              False
  